### ISSUE TITLE
does scato solve the typeclass hierarchy search problem?

### ISSUE THREAD

**Issue by fommil** [aloiscochard/scato#15]
apologies for asking, I wasn't able to see the answer from reading the examples.

There is the classic problem where if there is a typeclass hierarchy like

```
trait Ordering[T]
trait Numeric[T] extends Ordering[T]
```

then if there are instances of `Numeric[T]` in `Numeric`'s implicit scope (e.g. its companion) then methods that require

```
def foo[T: Ordering](t: T) = ...
```

will fail to resolve the `Ordering` unless there is something that brings the `Numeric` scope into the game, such as

```
implicit def fromNumeric[T](N: Numeric[T]): Ordering[T] = N
```

do you have any solution for that?

(btw, I think the above `implicit def` could be generated automatically by ensime for a given unsealed codebase, but that's a different story...)

**Comment by jbgi** [comment]
there is no magic here. there is indeed need to bring `implicit` `def`s like `fromNumeric` into scope for the subtyping-free encoding to works. This is can be done via a "prelude" import, eg., in scalaz8, when you import `scalaz._` you get into scope the implicits defined in https://github.com/scalaz/scalaz/blob/series/8.0.x/base/shared/src/main/scala/scalaz/BaseHierarchy.scala

**Comment by fommil** [comment]
Thanks!

**Comment by aloiscochard** [comment]
Thanks @jbgi :-)
